services:
  comfyui:
    image: pictorial/whalecomfy:v1.0.0
    build: .
    volumes:
      - ${CLONE_DIR}/models:/ComfyUI/models:rw
      - ${CLONE_DIR}/custom_nodes:/ComfyUI/custom_nodes:rw
      - ${CLONE_DIR}/venv:/ComfyUI/venv:rw
      - ${CLONE_DIR}/output:/ComfyUI/output:rw
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    stop_signal: SIGKILL
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  comfy-proxy:
    image: pictorial/comfy-proxy:v1.0.0
    stop_signal: SIGKILL
    ports:
      - ${server_port}:8081  # 连接到同一个网络
    depends_on:
      - comfyui  # 确保 comfyui 先启动

  download_models_linux:
    image: pictorial/comfy-proxy:v1.0.0
    volumes:
      - ${CLONE_DIR}/models:/ComfyUI/models:rw
      - ${CLONE_DIR}/custom_nodes:/ComfyUI/custom_nodes:rw
      - ./scripts:/app/scripts:r
    entrypoint: python /app/scripts/models_down.py
    working_dir: /ComfyUI
    stop_signal: SIGKILL
    restart: "no"
    labels:
      - "com.docker.compose.autoremove=true"